"""auction/buyer relationship fixed

Revision ID: 14f25c67e77a
Revises: 4c84fcee8525
Create Date: 2024-10-16 16:33:38.706426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14f25c67e77a'
down_revision: Union[str, None] = '4c84fcee8525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction', 'buyer_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction', 'buyer_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
