"""auction status

Revision ID: 1617002c4906
Revises: de6499eb1a4e
Create Date: 2024-10-17 04:11:17.870015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1617002c4906'
down_revision: Union[str, None] = 'de6499eb1a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('auction_status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', name='auctionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'auction_status')
    # ### end Alembic commands ###
