"""added phone to buyer billing

Revision ID: 1bcce9324f21
Revises: b83bbb6c168e
Create Date: 2024-10-21 22:29:31.502101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcce9324f21'
down_revision: Union[str, None] = 'b83bbb6c168e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_billing', sa.Column('phone_number', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_billing', 'phone_number')
    # ### end Alembic commands ###
