"""removed auction quantity

Revision ID: 3d74139ece9f
Revises: af108c8090b6
Create Date: 2024-10-17 13:35:05.056971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d74139ece9f'
down_revision: Union[str, None] = 'af108c8090b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'quantity_sold')
    op.drop_column('auction', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('auction', sa.Column('quantity_sold', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
