"""billing update

Revision ID: 46cd4f730112
Revises: d441a50de37b
Create Date: 2024-10-21 21:15:01.803540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46cd4f730112'
down_revision: Union[str, None] = 'd441a50de37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_billing', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('tax_id', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('postal_code', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('phone_number', sa.String(length=255), nullable=False))
    op.add_column('company_billing', sa.Column('bank_account', sa.String(length=255), nullable=False))
    op.drop_column('company_billing', 'company_details')
    op.add_column('user_billing', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('user_billing', sa.Column('postal_code', sa.String(length=255), nullable=False))
    op.add_column('user_billing', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('user_billing', sa.Column('country', sa.String(length=255), nullable=False))
    op.drop_column('user_billing', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_billing', sa.Column('details', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user_billing', 'country')
    op.drop_column('user_billing', 'city')
    op.drop_column('user_billing', 'postal_code')
    op.drop_column('user_billing', 'address')
    op.add_column('company_billing', sa.Column('company_details', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('company_billing', 'bank_account')
    op.drop_column('company_billing', 'phone_number')
    op.drop_column('company_billing', 'country')
    op.drop_column('company_billing', 'city')
    op.drop_column('company_billing', 'postal_code')
    op.drop_column('company_billing', 'address')
    op.drop_column('company_billing', 'tax_id')
    op.drop_column('company_billing', 'name')
    # ### end Alembic commands ###
