"""many structure changes auction/buyer

Revision ID: 4c84fcee8525
Revises: c3c259482ec3
Create Date: 2024-10-16 13:56:27.311731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c84fcee8525'
down_revision: Union[str, None] = 'c3c259482ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('auction_type', sa.Enum('BUY_NOW', 'BID', name='auctiontype'), nullable=False))
    op.add_column('auction', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('auction', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auction', 'buyer', ['buyer_id'], ['id'])
    op.drop_column('auction', 'role')
    op.drop_column('auction', 'bid_available')
    op.drop_column('auction', 'buy_now_available')
    op.add_column('bid', sa.Column('current_bid_winner_id', sa.Integer(), nullable=False))
    op.drop_constraint('bid_ibfk_1', 'bid', type_='foreignkey')
    op.drop_constraint('bid_ibfk_2', 'bid', type_='foreignkey')
    op.create_foreign_key(None, 'bid', 'buyer', ['current_bid_winner_id'], ['id'])
    op.drop_column('bid', 'product_id')
    op.drop_column('bid', 'higher_bidder_id')
    op.drop_constraint('product_ibfk_2', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_3', 'product', type_='foreignkey')
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'status')
    op.drop_column('product', 'seller_id')
    op.drop_column('product', 'end_date')
    op.drop_column('product', 'buyer_id')
    op.drop_column('product', 'price')
    op.drop_column('product', 'quantity')
    op.drop_column('product', 'isBid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('isBid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.add_column('product', sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('end_date', mysql.DATETIME(), nullable=False))
    op.add_column('product', sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('status', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('product', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.create_foreign_key('product_ibfk_3', 'product', 'buyer', ['buyer_id'], ['id'])
    op.create_foreign_key('product_ibfk_2', 'product', 'buyer', ['seller_id'], ['id'])
    op.add_column('bid', sa.Column('higher_bidder_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bid', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.create_foreign_key('bid_ibfk_2', 'bid', 'buyer', ['higher_bidder_id'], ['id'])
    op.create_foreign_key('bid_ibfk_1', 'bid', 'product', ['product_id'], ['id'])
    op.drop_column('bid', 'current_bid_winner_id')
    op.add_column('auction', sa.Column('buy_now_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('auction', sa.Column('bid_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('auction', sa.Column('role', mysql.ENUM('ACTIVE', 'INACTIVE', 'FINISHED'), nullable=True))
    op.drop_constraint(None, 'auction', type_='foreignkey')
    op.drop_column('auction', 'buyer_id')
    op.drop_column('auction', 'quantity')
    op.drop_column('auction', 'auction_type')
    # ### end Alembic commands ###
