"""removed status from Category

Revision ID: 5dcdbbced6ce
Revises: 14f25c67e77a
Create Date: 2024-10-16 17:13:23.150431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dcdbbced6ce'
down_revision: Union[str, None] = '14f25c67e77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('status', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
