"""added state to billing

Revision ID: 6ac91bcc5733
Revises: abd7768a5aa9
Create Date: 2024-10-22 17:40:52.143589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac91bcc5733'
down_revision: Union[str, None] = 'abd7768a5aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_billing', sa.Column('state', sa.String(length=255), nullable=False))
    op.add_column('user_billing', sa.Column('state', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_billing', 'state')
    op.drop_column('company_billing', 'state')
    # ### end Alembic commands ###
