"""decimal to float

Revision ID: 6eebf48b8f46
Revises: be235ebe8f92
Create Date: 2024-10-17 00:10:23.217748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6eebf48b8f46'
down_revision: Union[str, None] = 'be235ebe8f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction', 'buy_now_price',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('bid', 'current_bid_value',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('bid_history', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('user', 'balance_available',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('user', 'balance_reserved',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance_reserved',
               existing_type=sa.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('user', 'balance_available',
               existing_type=sa.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('bid_history', 'amount',
               existing_type=sa.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('bid', 'current_bid_value',
               existing_type=sa.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('auction', 'buy_now_price',
               existing_type=sa.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
