"""billing update2

Revision ID: 8bd952bac447
Revises: 46cd4f730112
Create Date: 2024-10-21 21:57:23.104771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd952bac447'
down_revision: Union[str, None] = '46cd4f730112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_billing', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('user_billing', sa.Column('last_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_billing', 'last_name')
    op.drop_column('user_billing', 'first_name')
    # ### end Alembic commands ###
