"""Add isBid to product

Revision ID: 94465a2507b8
Revises: 75249a61b316
Create Date: 2024-10-06 18:54:19.220321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94465a2507b8'
down_revision: Union[str, None] = '75249a61b316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('isBid', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'isBid')
    # ### end Alembic commands ###
