"""added wallet transaction and account type

Revision ID: a2e08c4bb7be
Revises: 3d74139ece9f
Create Date: 2024-10-18 15:16:14.165167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2e08c4bb7be'
down_revision: Union[str, None] = '3d74139ece9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('account_type', sa.Enum('PERSONAL', 'BUSINESS', 'BUSINESS_UNVERIFIED', name='useraccounttype'), nullable=True))
    op.add_column('wallet_transaction', sa.Column('stripe_payment_id', sa.String(length=255), nullable=True))
    op.drop_column('wallet_transaction', 'stripe_payment_intent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transaction', sa.Column('stripe_payment_intent_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('wallet_transaction', 'stripe_payment_id')
    op.drop_column('buyer', 'account_type')
    # ### end Alembic commands ###
