"""stripe2

Revision ID: a6d8d03e44ee
Revises: 356221acd3ac
Create Date: 2024-10-18 15:38:44.076050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6d8d03e44ee'
down_revision: Union[str, None] = '356221acd3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transaction', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('wallet_transaction', sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
    op.drop_column('wallet_transaction', 'stripe_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transaction', sa.Column('stripe_payment_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('wallet_transaction', 'stripe_checkout_session_id')
    op.drop_column('wallet_transaction', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
