"""removed address table

Revision ID: abd7768a5aa9
Revises: 1bcce9324f21
Create Date: 2024-10-21 22:55:33.769959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abd7768a5aa9'
down_revision: Union[str, None] = '1bcce9324f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_id', table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('zip', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_address_id', 'address', ['id'], unique=False)
    # ### end Alembic commands ###
