"""auction quantity modify

Revision ID: af108c8090b6
Revises: 1617002c4906
Create Date: 2024-10-17 13:10:03.483949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af108c8090b6'
down_revision: Union[str, None] = '1617002c4906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('quantity_sold', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'quantity_sold')
    # ### end Alembic commands ###
