"""removed adress

Revision ID: b83bbb6c168e
Revises: 15075c2e427b
Create Date: 2024-10-21 22:24:59.360742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b83bbb6c168e'
down_revision: Union[str, None] = '15075c2e427b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_ibfk_1', 'user', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
