"""Initial migration

Revision ID: dd7ec0ba9104
Revises: 
Create Date: 2024-07-03 17:58:54.836868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7ec0ba9104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'user_id')
    op.add_column('user', sa.Column('address_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address_id')
    op.add_column('address', sa.Column('user_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
